# version of the docker compose sintax
version: '3.9'

services:
  app:
    build:
      #build the docker file inside our current directory we are running docker-compose
      context: .
      # if we are running this docker-compose set build argument Dev=true
      args:
        - DEV=true
    #port 8000 on local to port 8000 in container
    ports:
      - "8000:8000"
    # mapping our system to docker container, to reflect local changes in project to running container (avoiding rebuilding the container)
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
